service:
  # nome do service
  name: ignitecertificate

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    # auxilia na execução no ambiente de desenvolvimento
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  bucket: serverlesscertificateignite

package:
  # todas funcionalidade são empacotadas de forma individual
  individualy: true

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  # Definindo permissões aws
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  generateCertificate:
    # caminho da função serverless
    handler: src/functions/generateCertificate.handle
    # formato que vai chamar nossa função serverless
    events: 
      - http:
        path: /generateCertificate
        method: POST
        cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:PutItem
        Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/users_certificates"
  verifyCertificate:
    # caminho da função serverless
    handler: src/functions/verifyCertificate.handle
    # formato que vai chamar nossa função serverless
    events: 
      - http:
        path: /verifyCertificate/{id}
        method: GET
        cors: true
        iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/users_certificates"

resources:
  # criando um banco de dados Dynamodb
  Resources:
    dbCertificateUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: users_certificates
        AttributeDefinitions:
          - AttributeName: id
          - AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH